In [1]:
#!/usr/bin/env python3
import pandas as pdr
import matplotlib.pyplot as plt

In [2]:
def get_requirements():
    print("Data Manipulation")
    print("\nProgram Requirements:")
    print("1. Data Cleaning and Manipulation.")
    print("2. Import necessary libraries.")
    print("3. Research how to install any missing packages, if necessary.")
    print("4. Create at least three functions that are called by the program.")
    print("\ta. main(): calls at least two other functions.")
    print("\tb. get_requirements(): displays the programs requirements.")
    print("\tc. data_manipulation(): displays the programs requirements.")
    print("5. Use imbd-movie-data.csv dataset.")
    print("6. When running program:")
    print("\ta. Document any issues.")
    print("\tb. Document solutions attempted.")
    print("\n***DataFram composed of three components: index, columns, and data. Data also known as values***")

In [3]:
def data_manipulation():
    my_path = r"C:\Users\Alex\lis4905_sum21\projects\ab16m\week8\imdb-movie-data.csv"
    df = pdr.read_csv(my_path)

    print("\n1. Print indexes:")
    print(df.index)

    print("\n2. Print columns: (Due to confidentiality, only attributes/features 'Time,' 'Amount,' and 'Class' available.")
    print(df.columns)

    print("\n3. Print data frame:")
    print(df)

    print("\n4. Print type:")
    print(type(df))

    print("\n5. Print attribute data types--object type represents strings:")
    print(df.dtypes)

    print("\n6. Print values (truncated list) in array format:")
    print(df.values)

    print("\n7. Print first 5 records, in non-array format:")
    print(df.head())

    print("\n8. Print index of all DataFrame columns names:")
    print(df.columns)

    print("\n9. Print DataFrame info (i.e., summary, similar to 'describe tablename;' in MySQL):")
    print(df.info())

    print("\n10. Print *only* number of DataFrame rows:")
    print(len(df))

    print("\n11. Print *only* number of DataFrame columns:")
    print(len(df.columns))

    print("\n12. Print number of DataFrame rows and columns:")
    print(df.shape)

    print("\n13. Print number of DataFrame elements (i.e., rows * columns):")
    print(df.size)

    print("\n14. Series: one-dimensional labeled array, can hold disparate date types")
    print("(e.g., integer, string, float, Boolean, Python objects, etc.):")
    my_list = [1, "Hello World", 3.5, True, 6, {"banana", "cherry", "apple"}]
    my_series = pdr.Series(my_list)
    print(my_series)

    print("\n15. DataFrame: multi-dimensional table, essentially, two Series.")
    print("Note: Various ways to create DataFrame.")
    print("Here, create dictionary (key:value pairs), ordered (since 3.7), mutable, and doesnot allow duplicates.")
    print("Then, pass it to pandas DataFrame constructor (Note: indexes automatically provided.):")
    vegetable = [3, 2, 0, 1, 5, 4, 7, 6]
    fruit = [0, 3, 7, 2, 1, 6, 4, 5]
    stuff = {"vegetables" : vegetable,
             "fruits" : fruit}
    names = ["Bob", "Jane", "Joe", "Peter", "Viola", "Thomas", "Raquel", "Nicole"]
    td_dataframe = pdr.DataFrame(data=stuff)
    print(td_dataframe)
    print("\nThen, add customer names as indexes:\n")
    td_dataframe2 = pdr.DataFrame(data=stuff, index=names)
    print(td_dataframe2)

    print("\nLocate customer's order by name:")
    print(td_dataframe2.loc["Jane"])

    print("\n17. Convert DataFrame to following file type: .csv and .json (save to same directory):")
    td_dataframe2.to_csv(path_or_buf=r"C:\Users\Alex\lis4905_sum21\projects\ab16m\week8\file.csv")
    td_dataframe2.to_json(path_or_buf=r"C:\Users\Alex\lis4905_sum21\projects\ab16m\week8\jfile.json")

    print("\n18. Create DataFrame for imdb-movie-data.csv, designate movie ***titles*** as index, and print 1st five records:")

    df.index = df["Title"]
    print(df)

    print("\n19. Display last three records:")
    print(df.tail(3))

    print("\n20. Handling duplicates using append(). (Note: Twice as many rows.):")
    df = df.append(df)
    print(df.shape)

    print("\n21. Cleaning duplicates using drop_duplicates():")
    df = df.drop_duplicates()
    print(df.shape)

    print("\n22. Cleaning column names using rename(), and list comprehension.")
    print("Original column names:")
    #df = pdr.read_csv(my_path)
    print(df.columns)
    print("\n22a. Remove parentheses using rename():")
    df = df.rename(columns={'Revenue (Millions)':"revenue_millions"})
    print(df.columns)
    print("\n22b. Make column names lower case, manually using list assignment")
    columns=['rank','title', 'genre', 'description', 'director', 'actors', 'year', 'runtime', 'rating', 'votes', 'revenue_millions', 'metascore']
    df.columns = columns
    print(df.columns)
    print("\n22c. Make column names lower case using list comprehension and lower():")
    df.columns = [i.lower() for i in df.columns]
    print(df.columns)
    print("23. Working with missing (null) values: 1) remove, or 2) replace (imputation).")
    print("\n\tStep 1: Identify null cells:")
    print(df.isna())
    print("\n\tStep2: Count number of nulls in each column:")
    print(df.isna().sum())
    print("\n\t23a. NB: Remove nulls, *only* with small amount of missing data (<5%): \n Note: dropna() removes rows w/at least one null value, \n and returns new DataFrame, w/o affecting original. \n axis=0 (rows default), axis = 1 columns \n Where does \'axis\' come from? Remember: df.shape returns rows(0)/cols(1).")
    print(df.dropna(axis=0))
    print("\t23b. Remove nulls (columns):")
    print(df.dropna(axis=1))
    print("\t23c. Imputation: Replace missing values with guessed/estimated value. \n Use data and relationships among non-missing predictors to estimate missing values.\n One (simple) way: Apply central tendency values (i.e., mean, median, mode).")
    print("\n\tStep 1: Extract column with null values into variable, and print 1st 5 records: \n Note: \"Title\" index remains.")
    print(df["revenue_millions"].head())
    print("\n\tStep 2: Return mean value:")
    print(df["revenue_millions"].mean())
    print("\n\tStep 3: Impute mean value using fillna() and inplace=True, then print nulls. \n Remember: inplace=True affects original DataFrame.")
    df["revenue_millions"].fillna(df["revenue_millions"].mean(),inplace=True)
    print(df.isna().sum())
    print("\n24. Basic statistical analyses using describe(), summary of *continuous* variables. \n Understanding data values (e.g., continuous vs. categorical) assists when determining plot types.")
    print(df.describe())
    print("\n25. Basic statistical analyses using describe(), summary of *categorical* variable (here, only *one* attribute). \n Returns row count, unique count of categories, top category, and freq of top categor(y/ies).")
    print(df['genre'].describe())
    print("\n26. Frequency of all (values_counts()) in a column (here, 'genre') returns 1st 10:")
    dataseries = df['genre'].squeeze()
    print(dataseries.value_counts().head(10))
    print("\n27. Relationships between variables using .corr() method:")
    print(df.corr())
    print("\n28. Conditional selections.")
    print("\n\t28a. Display oldest and newest release years for movies is dataset:")
    max_y = df["year"].max()
    min_y = df["year"].min()
    print(f"Oldest: {max_y}, Newest: {min_y}")
    
    print("\n\t28b. Filter by one director, return 3 records:")
    print(df[df['director']=="Clint Eastwood"].head(3))
    print("\n\t28c. Filter by rating (>=8.0), return 3 records:")
    print(df[df['rating']>=8.0].head(3))
    print("\n\t28d. Filter by two directors (using 'or'). Logical operators | for 'or' & for 'and', return 1st 5 records:")
    print(df[(df['director']=="James Gunn") | (df['director']=="Clint Eastwood")].head(5))
    print("\n\t28e. Filter by same two directories (using 'isin'), return 1st 5 records:")
    directors = ["Clint Eastwood", "James Gunn"]
    print(df[df['director'].isin(directors)].head(5))
    print("\n\t28f. Filter by all movies released between 2005 and 2010, inclusive, having rating above 8.5:")
    print(df[(df['year'] >= 2005) & (df['year'] <= 2010) & (df['rating'] > 8.5)])
    print("\n\t28g. Filter by all movies released between 2005 and 2010, inclusive, having rating above 8.0, and made above or equal to 25th percentile in revenue:")
    q75 = df['revenue_millions'].quantile(0.75)
    print(df[(df['year'] >= 2005) & (df['year'] <= 2010) & (df['rating'] > 8.0) & (df['revenue_millions'] > q75) ])
    print("\n29. Crate function, watch_rating(), return 'yes' or 'no' based upon 8.5 or greater rating. \nUse Python's apply() function to pass 'rating' attribute to function,\nand assign return values to new attribute 'watch_movie', display 1st 10 rows.")
    def watch_rating(rating):
        if rating > 8.5:
            return "Yes"
        else:
            return "False"

    df['watch_rating'] = df['rating'].apply(func=watch_rating)
    print(df.head(10))

In [4]:
def main():
    get_requirements()
    data_manipulation()

In [5]:
if __name__ == "__main__":
    main()

Data Manipulation

Program Requirements:
1. Data Cleaning and Manipulation.
2. Import necessary libraries.
3. Research how to install any missing packages, if necessary.
4. Create at least three functions that are called by the program.
	a. main(): calls at least two other functions.
	b. get_requirements(): displays the programs requirements.
	c. data_manipulation(): displays the programs requirements.
5. Use imbd-movie-data.csv dataset.
6. When running program:
	a. Document any issues.
	b. Document solutions attempted.

***DataFram composed of three components: index, columns, and data. Data also known as values***

1. Print indexes:
RangeIndex(start=0, stop=1000, step=1)

2. Print columns: (Due to confidentiality, only attributes/features 'Time,' 'Amount,' and 'Class' available.
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

3. Print data frame:
     Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1       2               Prometheus  Adventure,Mystery,Sci-Fi
2       3                    Split           Horror,Thriller
3       4                     Sing   Animation,Comedy,Family
4       5            Suicide Squad  Action,Adventure,Fantasy
..    ...                      ...                       ...
995   996     Secret in Their Eyes       Crime,Drama,Mystery
996   997          Hostel: Part II                    Horror
997   998   Step Up 2: The Streets       Drama,Music,Romance
998   999             Search Party          Adventure,Comedy
999  1000               Nine Lives     Comedy,Family,Fantasy

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn
1    Following clues to the origin of mankind, a te...          Ridley Scott
2    Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3    In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4    A secret government agency recruits some of th...            David Ayer
..                                                 ...                   ...
995  A tight-knit team of rising investigators, alo...             Billy Ray
996  Three American college students studying abroa...              Eli Roth
997  Romantic sparks occur between two dance studen...            Jon M. Chu
998  A pair of friends embark on a mission to reuni...        Scot Armstrong
999  A stuffy businessman finds himself trapped ins...      Barry Sonnenfeld

                                                Actors  Year  \
0    Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014
1    Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012
2    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016
3    Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016
4    Will Smith, Jared Leto, Margot Robbie, Viola D...  2016
..                                                 ...   ...
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating   Votes  Revenue (Millions)  Metascore
0                  121     8.1  757074              333.13       76.0
1                  124     7.0  485820              126.46       65.0
2                  117     7.3  157606              138.12       62.0
3                  108     7.2   60545              270.32       59.0
4                  123     6.2  393727              325.02       40.0
..                 ...     ...     ...                 ...        ...
995                111     6.2   27585                 NaN       45.0
996                 94     5.5   73152               17.54       46.0
997                 98     6.2   70699               58.01       50.0
998                 93     5.6    4881                 NaN       22.0
999                 87     5.3   12435               19.64       11.0

[1000 rows x 12 columns]

4. Print type:
<class 'pandas.core.frame.DataFrame'>

5. Print attribute data types--object type represents strings:
Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

6. Print values (truncated list) in array format:
[[1 'Guardians of the Galaxy' 'Action,Adventure,Sci-Fi' ... 757074 333.13
  76.0]
 [2 'Prometheus' 'Adventure,Mystery,Sci-Fi' ... 485820 126.46 65.0]
 [3 'Split' 'Horror,Thriller' ... 157606 138.12 62.0]
 ...
 [998 'Step Up 2: The Streets' 'Drama,Music,Romance' ... 70699 58.01 50.0]
 [999 'Search Party' 'Adventure,Comedy' ... 4881 nan 22.0]
 [1000 'Nine Lives' 'Comedy,Family,Fantasy' ... 12435 19.64 11.0]]

7. Print first 5 records, in non-array format:
   Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore
0     8.1  757074              333.13       76.0
1     7.0  485820              126.46       65.0
2     7.3  157606              138.12       62.0
3     7.2   60545              270.32       59.0
4     6.2  393727              325.02       40.0

8. Print index of all DataFrame columns names:
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

9. Print DataFrame info (i.e., summary, similar to 'describe tablename;' in MySQL):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB
None

10. Print *only* number of DataFrame rows:
1000

11. Print *only* number of DataFrame columns:
12

12. Print number of DataFrame rows and columns:
(1000, 12)

13. Print number of DataFrame elements (i.e., rows * columns):
12000

14. Series: one-dimensional labeled array, can hold disparate date types
(e.g., integer, string, float, Boolean, Python objects, etc.):
0                          1
1                Hello World
2                        3.5
3                       True
4                          6
5    {banana, apple, cherry}
dtype: object

15. DataFrame: multi-dimensional table, essentially, two Series.
Note: Various ways to create DataFrame.
Here, create dictionary (key:value pairs), ordered (since 3.7), mutable, and doesnot allow duplicates.
Then, pass it to pandas DataFrame constructor (Note: indexes automatically provided.):
   vegetables  fruits
0           3       0
1           2       3
2           0       7
3           1       2
4           5       1
5           4       6
6           7       4
7           6       5

Then, add customer names as indexes:

        vegetables  fruits
Bob              3       0
Jane             2       3
Joe              0       7
Peter            1       2
Viola            5       1
Thomas           4       6
Raquel           7       4
Nicole           6       5

Locate customer's order by name:
vegetables    2
fruits        3
Name: Jane, dtype: int64

17. Convert DataFrame to following file type: .csv and .json (save to same directory):

18. Create DataFrame for imdb-movie-data.csv, designate movie ***titles*** as index, and print 1st five records:
                         Rank                    Title  \
Title
Guardians of the Galaxy     1  Guardians of the Galaxy
Prometheus                  2               Prometheus
Split                       3                    Split
Sing                        4                     Sing
Suicide Squad               5            Suicide Squad
...                       ...                      ...
Secret in Their Eyes      996     Secret in Their Eyes
Hostel: Part II           997          Hostel: Part II
Step Up 2: The Streets    998   Step Up 2: The Streets
Search Party              999             Search Party
Nine Lives               1000               Nine Lives

                                            Genre  \
Title
Guardians of the Galaxy   Action,Adventure,Sci-Fi
Prometheus               Adventure,Mystery,Sci-Fi
Split                             Horror,Thriller
Sing                      Animation,Comedy,Family
Suicide Squad            Action,Adventure,Fantasy
...                                           ...
Secret in Their Eyes          Crime,Drama,Mystery
Hostel: Part II                            Horror
Step Up 2: The Streets        Drama,Music,Romance
Search Party                     Adventure,Comedy
Nine Lives                  Comedy,Family,Fantasy

                                                               Description  \
Title
Guardians of the Galaxy  A group of intergalactic criminals are forced ...
Prometheus               Following clues to the origin of mankind, a te...
Split                    Three girls are kidnapped by a man with a diag...
Sing                     In a city of humanoid animals, a hustling thea...
Suicide Squad            A secret government agency recruits some of th...
...                                                                    ...
Secret in Their Eyes     A tight-knit team of rising investigators, alo...
Hostel: Part II          Three American college students studying abroa...
Step Up 2: The Streets   Romantic sparks occur between two dance studen...
Search Party             A pair of friends embark on a mission to reuni...
Nine Lives               A stuffy businessman finds himself trapped ins...

                                     Director  \
Title
Guardians of the Galaxy            James Gunn
Prometheus                       Ridley Scott
Split                      M. Night Shyamalan
Sing                     Christophe Lourdelet
Suicide Squad                      David Ayer
...                                       ...
Secret in Their Eyes                Billy Ray
Hostel: Part II                      Eli Roth
Step Up 2: The Streets             Jon M. Chu
Search Party                   Scot Armstrong
Nine Lives                   Barry Sonnenfeld

                                                                    Actors  \
Title
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...
...                                                                    ...
Secret in Their Eyes     Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...
Hostel: Part II          Lauren German, Heather Matarazzo, Bijou Philli...
Step Up 2: The Streets   Robert Hoffman, Briana Evigan, Cassie Ventura,...
Search Party             Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
Nine Lives               Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...

                         Year  Runtime (Minutes)  Rating   Votes  \
Title
Guardians of the Galaxy  2014                121     8.1  757074
Prometheus               2012                124     7.0  485820
Split                    2016                117     7.3  157606
Sing                     2016                108     7.2   60545
Suicide Squad            2016                123     6.2  393727
...                       ...                ...     ...     ...
Secret in Their Eyes     2015                111     6.2   27585
Hostel: Part II          2007                 94     5.5   73152
Step Up 2: The Streets   2008                 98     6.2   70699
Search Party             2014                 93     5.6    4881
Nine Lives               2016                 87     5.3   12435

                         Revenue (Millions)  Metascore
Title
Guardians of the Galaxy              333.13       76.0
Prometheus                           126.46       65.0
Split                                138.12       62.0
Sing                                 270.32       59.0
Suicide Squad                        325.02       40.0
...                                     ...        ...
Secret in Their Eyes                    NaN       45.0
Hostel: Part II                       17.54       46.0
Step Up 2: The Streets                58.01       50.0
Search Party                            NaN       22.0
Nine Lives                            19.64       11.0

[1000 rows x 12 columns]

19. Display last three records:
                        Rank                   Title                  Genre  \
Title
Step Up 2: The Streets   998  Step Up 2: The Streets    Drama,Music,Romance
Search Party             999            Search Party       Adventure,Comedy
Nine Lives              1000              Nine Lives  Comedy,Family,Fantasy

                                                              Description  \
Title
Step Up 2: The Streets  Romantic sparks occur between two dance studen...
Search Party            A pair of friends embark on a mission to reuni...
Nine Lives              A stuffy businessman finds himself trapped ins...

                                Director  \
Title
Step Up 2: The Streets        Jon M. Chu
Search Party              Scot Armstrong
Nine Lives              Barry Sonnenfeld

                                                                   Actors  \
Title
Step Up 2: The Streets  Robert Hoffman, Briana Evigan, Cassie Ventura,...
Search Party            Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
Nine Lives              Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...

                        Year  Runtime (Minutes)  Rating  Votes  \
Title
Step Up 2: The Streets  2008                 98     6.2  70699
Search Party            2014                 93     5.6   4881
Nine Lives              2016                 87     5.3  12435

                        Revenue (Millions)  Metascore
Title
Step Up 2: The Streets               58.01       50.0
Search Party                           NaN       22.0
Nine Lives                           19.64       11.0

20. Handling duplicates using append(). (Note: Twice as many rows.):
(2000, 12)

21. Cleaning duplicates using drop_duplicates():
(1000, 12)

22. Cleaning column names using rename(), and list comprehension.
Original column names:
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

22a. Remove parentheses using rename():
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'revenue_millions',
       'Metascore'],
      dtype='object')

22b. Make column names lower case, manually using list assignment
Index(['rank', 'title', 'genre', 'description', 'director', 'actors', 'year',
       'runtime', 'rating', 'votes', 'revenue_millions', 'metascore'],
      dtype='object')

22c. Make column names lower case using list comprehension and lower():
Index(['rank', 'title', 'genre', 'description', 'director', 'actors', 'year',
       'runtime', 'rating', 'votes', 'revenue_millions', 'metascore'],
      dtype='object')
23. Working with missing (null) values: 1) remove, or 2) replace (imputation).

	Step 1: Identify null cells:
                          rank  title  genre  description  director  actors  \
Title
Guardians of the Galaxy  False  False  False        False     False   False
Prometheus               False  False  False        False     False   False
Split                    False  False  False        False     False   False
Sing                     False  False  False        False     False   False
Suicide Squad            False  False  False        False     False   False
...                        ...    ...    ...          ...       ...     ...
Secret in Their Eyes     False  False  False        False     False   False
Hostel: Part II          False  False  False        False     False   False
Step Up 2: The Streets   False  False  False        False     False   False
Search Party             False  False  False        False     False   False
Nine Lives               False  False  False        False     False   False

                          year  runtime  rating  votes  revenue_millions  \
Title
Guardians of the Galaxy  False    False   False  False             False
Prometheus               False    False   False  False             False
Split                    False    False   False  False             False
Sing                     False    False   False  False             False
Suicide Squad            False    False   False  False             False
...                        ...      ...     ...    ...               ...
Secret in Their Eyes     False    False   False  False              True
Hostel: Part II          False    False   False  False             False
Step Up 2: The Streets   False    False   False  False             False
Search Party             False    False   False  False              True
Nine Lives               False    False   False  False             False

                         metascore
Title
Guardians of the Galaxy      False
Prometheus                   False
Split                        False
Sing                         False
Suicide Squad                False
...                            ...
Secret in Their Eyes         False
Hostel: Part II              False
Step Up 2: The Streets       False
Search Party                 False
Nine Lives                   False

[1000 rows x 12 columns]

	Step2: Count number of nulls in each column:
rank                  0
title                 0