In [1]:
import pandas as pd

In [2]:
def get_requirements():
    print("Deep Manipulation\n")
    print("Program Requirements:")
    print("1. Build deep-learning model to detect diabetes possibility.")
    print("2. Import libraries")
    print("3. Reasearch how to install any missing packages.")
    print("4. Create at least three functions that are called by the program:")
    print("\ta. main(): calls at least two other functions.")
    print("\tb. get_requirements(): displays the program requirements.")
    print("\tc. deep_learning(): displays the following data.")
    print("5. Use imdb dataset")
    print('6. When running program')
    print("\ta. Document any issues.")
    print("\tb. Document solutions attempted.")

In [3]:
def main():
    uri = "imdb-movie-data.csv"
    df = pd.read_csv(uri)

    print("\n1: Print indexes")
    print(df.index)
    print("\n2: Print columns")
    print(df.columns)
    print("\n3: Print data frame")
    print(df.head(5))
    print(df.tail(5))
    print("\n4: Print type")
    print(type(df))
    print("\n5: Print data attribute type")
    print(df.dtypes)
    print("\n6: Print values in array format")
    print(df.values)
    print("\n7: Print index of all column names")
    print(df[0:5])
    print("\n8: Print data frame info")
    print(df.columns)
    print("\nPrint summary stats")
    print(df.info(verbose=True))
    print("\n9: Number of rows")
    print(df.info())
    print("\n10: Number of columns")
    print(len(df))
    print("\n11: Number of rows and columns")
    print(len(df.columns))
    print("\n13: Number of elements")
    print(df.size)
    print("\n14. Series one dimensional labled array")
    data = [1, 'Hello World', 3.5, 'True', 6, {'banna', 'cherry', 'apple'}]
    print(data)
    
    print("\n15. Dataframe multi-dimensional table, 2 series")
    dic = {'vegetables': [3,2,0,1,5,4,7,6],'fruits':[0,3,7,2,1,6,4,5]}
    df1 = pd.DataFrame(dic)
    print(df1)
    
    print("Then add customer name as index")
    data = {'vegetables':[3,2,0,1,5,4,7,6],'fruit':[0,3,7,2,1,6,4,5]}
    df_data = pd.DataFrame(data,['Bob', 'Jane', 'Joe', 'Peter', 'Viola', 'Thomas', 'Rauel', 'Nicole'])
    print(df1)
    
    print("\n16. Locate customer order by name")
    print(df_data.loc['Jane',:])
    
    print("\n17. Convert dataframe to .csv and .json")
    df1.to_csv('produce_list.csv')
    df1.to_json('produce_list.json')
    
    print("\n18. Create dataframe for for imdb csv, designate movie titles as index print 5 records")
    df = pd.read_csv('imdb-movie-data.csv')
    df = df.set_index('Title')
    print(df.head())
    
    print("\n19. Print last 3 records")
    print(df.tail(3))
    
    print("\n20. Handling duplicates using append()")
    df = df.append(df)
    print(df.shape)
    
    print("\n21. Cleaning duplicates using drop_duplicates")
    df = df.drop_duplicates()
    print(df.shape)
    
    print("\n22. Cleaning column using rename()")
    print(df.columns)
    
    print("\n22a. Remove parens using rename()")
    df = df.rename(columns = {'Revenue (Millions)':" "})
    print(df.columns)
    
    print("\n22b. Make columns lowercase")
    columns = ['rank', 'genre', 'description', 'director', 'actors', 'year', 'runtime', 'rating', 'votes', 'revenue_millions', 'metascore']
    df.columns = columns
    print(df.columns)
    
    print("\n23. Working with missing values 1. remove, 2. replace")
    
    print("\n23 Step 1. Identify nulls")
    print(df.isna())
    
    print("\n23 Step 2. Count number of nulls")
    print(df.isna().sum())
    
    print("\n23a. NB remove nulls with small amount of missing data")
    print(df.dropna(axis=0))
    
    print("\n23B. remove null columns")
    print(df.dropna(axis=1))
    
    print("\n23C. Imputation replacing missing values with guessed values")
    print("\nStep 1. extract columbs")
    print(df["revenue_millions"].head())
    
    
    print("\n24. Basic statistical analysis using describe() summary of continous variables")
    print(df.describe())
    
    print("\n25. Basic statistical analysis using describe() summary of categorical variables")
    print(df['genre'].describe())
    
    print("\n26. Frequency of all values, return 1st 10")
    print(df['genre'].value_counts().head(10))
    
    print("\n27. Relationships betwen continuous variables using .corr() method: ")
    column_1 = df["revenue_millions"]
    column_2 = df["votes"]
    correlation = column_1.corr(column_2)
    correlation_df = df.corr()
    print(correlation_df)
    
    print("\n28. Condition selections")
    print("\n28a. Display oldest and newest release years for movies in dataset")
    min = df['year'].min()
    max = df['year'].max()
    print(f"oldest {min} newest {max}")
    
    print("\n28b. filter by one director return 3 records")
    director = ['Martin Scorsese']
    df_director = df.loc[df['director'].isin(director)]
    print(df_director.head(3))
    
    print("\n28c. Filter by rating, return 3 records")
    print(df.loc[df['rating'] >= 8 ].head(3))
    
    print("\n28d. Filter by 2 directors using 'or'. Logical operators | for or and and")
    logic = df.loc[(df['director']=='Clint Eastwood') | (df['director']== 'James Gunn')]
    print(logic.head(5))
    
    print("\n28e. Filter by same 2 directors return 5")
    print(df['director'].isin(['Clint Eastwood', 'James Gunn']).head(5))
    
    print("\n28f. Filter by all movies released between 2005 and 2010 and has a rating above 8.5")
    print(df.loc[(df['year'] >= 2005) & (df['year'] <= 2010) & (df['rating'] > 8.5)].head(5))
    
    print("\n28g. Filter  by all movies between 2005 and 2010 and has a rating above 8.0 and made above or equal to the 25th percentile")
    print(df.loc[(df['year'] >= 2005) & (df['year'] <= 2010) & (df['rating'] > 8.0) % (df['revenue_millions'] >= 25)])
    
    print("\n29. Create a function watch_rating that returns yes or no based upon a 8.5 or greater rating")
    def watch(rating):
        if rating >= 8.5:
            return "NO"
        elif rating < 8.5:
            return "YES"
    df['rating'] = df['rating'].apply(watch)
    print(df.head(10))

In [4]:
get_requirements()
main()

Deep Manipulation

Program Requirements:
1. Build deep-learning model to detect diabetes possibility.
2. Import libraries
3. Reasearch how to install any missing packages.
4. Create at least three functions that are called by the program:
	a. main(): calls at least two other functions.
	b. get_requirements(): displays the program requirements.
	c. deep_learning(): displays the following data.
5. Use imdb dataset
6. When running program
	a. Document any issues.
	b. Document solutions attempted.

1: Print indexes
RangeIndex(start=0, stop=1000, step=1)

2: Print columns
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

3: Print data frame
   Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore
0     8.1  757074              333.13       76.0
1     7.0  485820              126.46       65.0
2     7.3  157606              138.12       62.0
3     7.2   60545              270.32       59.0
4     6.2  393727              325.02       40.0
     Rank                   Title                  Genre  \
995   996    Secret in Their Eyes    Crime,Drama,Mystery
996   997         Hostel: Part II                 Horror
997   998  Step Up 2: The Streets    Drama,Music,Romance
998   999            Search Party       Adventure,Comedy
999  1000              Nine Lives  Comedy,Family,Fantasy

                                           Description          Director  \
995  A tight-knit team of rising investigators, alo...         Billy Ray
996  Three American college students studying abroa...          Eli Roth
997  Romantic sparks occur between two dance studen...        Jon M. Chu
998  A pair of friends embark on a mission to reuni...    Scot Armstrong
999  A stuffy businessman finds himself trapped ins...  Barry Sonnenfeld

                                                Actors  Year  \
995  Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...  2015
996  Lauren German, Heather Matarazzo, Bijou Philli...  2007
997  Robert Hoffman, Briana Evigan, Cassie Ventura,...  2008
998  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014
999  Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016

     Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore
995                111     6.2  27585                 NaN       45.0
996                 94     5.5  73152               17.54       46.0
997                 98     6.2  70699               58.01       50.0
998                 93     5.6   4881                 NaN       22.0
999                 87     5.3  12435               19.64       11.0

4: Print type
<class 'pandas.core.frame.DataFrame'>

5: Print data attribute type
Rank                    int64
Title                  object
Genre                  object
Description            object
Director               object
Actors                 object
Year                    int64
Runtime (Minutes)       int64
Rating                float64
Votes                   int64
Revenue (Millions)    float64
Metascore             float64
dtype: object

6: Print values in array format
[[1 'Guardians of the Galaxy' 'Action,Adventure,Sci-Fi' ... 757074 333.13
  76.0]
 [2 'Prometheus' 'Adventure,Mystery,Sci-Fi' ... 485820 126.46 65.0]
 [3 'Split' 'Horror,Thriller' ... 157606 138.12 62.0]
 ...
 [998 'Step Up 2: The Streets' 'Drama,Music,Romance' ... 70699 58.01 50.0]
 [999 'Search Party' 'Adventure,Comedy' ... 4881 nan 22.0]
 [1000 'Nine Lives' 'Comedy,Family,Fantasy' ... 12435 19.64 11.0]]

7: Print index of all column names
   Rank                    Title                     Genre  \
0     1  Guardians of the Galaxy   Action,Adventure,Sci-Fi
1     2               Prometheus  Adventure,Mystery,Sci-Fi
2     3                    Split           Horror,Thriller
3     4                     Sing   Animation,Comedy,Family
4     5            Suicide Squad  Action,Adventure,Fantasy

                                         Description              Director  \
0  A group of intergalactic criminals are forced ...            James Gunn
1  Following clues to the origin of mankind, a te...          Ridley Scott
2  Three girls are kidnapped by a man with a diag...    M. Night Shyamalan
3  In a city of humanoid animals, a hustling thea...  Christophe Lourdelet
4  A secret government agency recruits some of th...            David Ayer

                                              Actors  Year  Runtime (Minutes)  \
0  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...  2014                121
1  Noomi Rapace, Logan Marshall-Green, Michael Fa...  2012                124
2  James McAvoy, Anya Taylor-Joy, Haley Lu Richar...  2016                117
3  Matthew McConaughey,Reese Witherspoon, Seth Ma...  2016                108
4  Will Smith, Jared Leto, Margot Robbie, Viola D...  2016                123

   Rating   Votes  Revenue (Millions)  Metascore
0     8.1  757074              333.13       76.0
1     7.0  485820              126.46       65.0
2     7.3  157606              138.12       62.0
3     7.2   60545              270.32       59.0
4     6.2  393727              325.02       40.0

8: Print data frame info
Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

Print summary stats
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB
None

9: Number of rows
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB
None

10: Number of columns
1000

11: Number of rows and columns
12

13: Number of elements
12000

14. Series one dimensional labled array
[1, 'Hello World', 3.5, 'True', 6, {'cherry', 'apple', 'banna'}]

15. Dataframe multi-dimensional table, 2 series
   vegetables  fruits
0           3       0
1           2       3
2           0       7
3           1       2
4           5       1
5           4       6
6           7       4
7           6       5
Then add customer name as index
   vegetables  fruits
0           3       0
1           2       3
2           0       7
3           1       2
4           5       1
5           4       6
6           7       4
7           6       5

16. Locate customer order by name
vegetables    2
fruit         3
Name: Jane, dtype: int64

17. Convert dataframe to .csv and .json

18. Create dataframe for for imdb csv, designate movie titles as index print 5 records
                         Rank                     Genre  \
Title
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi
Prometheus                  2  Adventure,Mystery,Sci-Fi
Split                       3           Horror,Thriller
Sing                        4   Animation,Comedy,Family
Suicide Squad               5  Action,Adventure,Fantasy

                                                               Description  \
Title
Guardians of the Galaxy  A group of intergalactic criminals are forced ...
Prometheus               Following clues to the origin of mankind, a te...
Split                    Three girls are kidnapped by a man with a diag...
Sing                     In a city of humanoid animals, a hustling thea...
Suicide Squad            A secret government agency recruits some of th...

                                     Director  \
Title
Guardians of the Galaxy            James Gunn
Prometheus                       Ridley Scott
Split                      M. Night Shyamalan
Sing                     Christophe Lourdelet
Suicide Squad                      David Ayer

                                                                    Actors  \
Title
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...

                         Year  Runtime (Minutes)  Rating   Votes  \
Title
Guardians of the Galaxy  2014                121     8.1  757074
Prometheus               2012                124     7.0  485820
Split                    2016                117     7.3  157606
Sing                     2016                108     7.2   60545
Suicide Squad            2016                123     6.2  393727

                         Revenue (Millions)  Metascore
Title
Guardians of the Galaxy              333.13       76.0
Prometheus                           126.46       65.0
Split                                138.12       62.0
Sing                                 270.32       59.0
Suicide Squad                        325.02       40.0

19. Print last 3 records
                        Rank                  Genre  \
Title
Step Up 2: The Streets   998    Drama,Music,Romance
Search Party             999       Adventure,Comedy
Nine Lives              1000  Comedy,Family,Fantasy

                                                              Description  \
Title
Step Up 2: The Streets  Romantic sparks occur between two dance studen...
Search Party            A pair of friends embark on a mission to reuni...
Nine Lives              A stuffy businessman finds himself trapped ins...

                                Director  \
Title
Step Up 2: The Streets        Jon M. Chu
Search Party              Scot Armstrong
Nine Lives              Barry Sonnenfeld

                                                                   Actors  \
Title
Step Up 2: The Streets  Robert Hoffman, Briana Evigan, Cassie Ventura,...
Search Party            Adam Pally, T.J. Miller, Thomas Middleditch,Sh...
Nine Lives              Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...

                        Year  Runtime (Minutes)  Rating  Votes  \
Title
Step Up 2: The Streets  2008                 98     6.2  70699
Search Party            2014                 93     5.6   4881
Nine Lives              2016                 87     5.3  12435

                        Revenue (Millions)  Metascore
Title
Step Up 2: The Streets               58.01       50.0
Search Party                           NaN       22.0
Nine Lives                           19.64       11.0

20. Handling duplicates using append()
(2000, 11)

21. Cleaning duplicates using drop_duplicates
(1000, 11)

22. Cleaning column using rename()
Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

22a. Remove parens using rename()
Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', ' ', 'Metascore'],
      dtype='object')

22b. Make columns lowercase
Index(['rank', 'genre', 'description', 'director', 'actors', 'year', 'runtime',
       'rating', 'votes', 'revenue_millions', 'metascore'],
      dtype='object')

23. Working with missing values 1. remove, 2. replace

23 Step 1. Identify nulls
                          rank  genre  description  director  actors   year  \
Title
Guardians of the Galaxy  False  False        False     False   False  False
Prometheus               False  False        False     False   False  False
Split                    False  False        False     False   False  False
Sing                     False  False        False     False   False  False
Suicide Squad            False  False        False     False   False  False
...                        ...    ...          ...       ...     ...    ...
Secret in Their Eyes     False  False        False     False   False  False
Hostel: Part II          False  False        False     False   False  False
Step Up 2: The Streets   False  False        False     False   False  False
Search Party             False  False        False     False   False  False
Nine Lives               False  False        False     False   False  False

                         runtime  rating  votes  revenue_millions  metascore
Title
Guardians of the Galaxy    False   False  False             False      False
Prometheus                 False   False  False             False      False
Split                      False   False  False             False      False
Sing                       False   False  False             False      False
Suicide Squad              False   False  False             False      False
...                          ...     ...    ...               ...        ...
Secret in Their Eyes       False   False  False              True      False
Hostel: Part II            False   False  False             False      False
Step Up 2: The Streets     False   False  False             False      False
Search Party               False   False  False              True      False
Nine Lives                 False   False  False             False      False

[1000 rows x 11 columns]

23 Step 2. Count number of nulls
rank                  0
genre                 0
description           0
director              0
actors                0
year                  0
runtime               0
rating                0
votes                 0
revenue_millions    128
metascore            64
dtype: int64

23a. NB remove nulls with small amount of missing data
                          rank                     genre  \
Title
Guardians of the Galaxy      1   Action,Adventure,Sci-Fi
Prometheus                   2  Adventure,Mystery,Sci-Fi
Split                        3           Horror,Thriller
Sing                         4   Animation,Comedy,Family
Suicide Squad                5  Action,Adventure,Fantasy
...                        ...                       ...
Resident Evil: Afterlife   994   Action,Adventure,Horror
Project X                  995                    Comedy
Hostel: Part II            997                    Horror
Step Up 2: The Streets     998       Drama,Music,Romance
Nine Lives                1000     Comedy,Family,Fantasy

                                                                description  \
Title
Guardians of the Galaxy   A group of intergalactic criminals are forced ...
Prometheus                Following clues to the origin of mankind, a te...
Split                     Three girls are kidnapped by a man with a diag...
Sing                      In a city of humanoid animals, a hustling thea...
Suicide Squad             A secret government agency recruits some of th...
...                                                                     ...
Resident Evil: Afterlife  While still out to destroy the evil Umbrella C...
Project X                 3 high school seniors throw a birthday party t...
Hostel: Part II           Three American college students studying abroa...
Step Up 2: The Streets    Romantic sparks occur between two dance studen...
Nine Lives                A stuffy businessman finds himself trapped ins...

                                      director  \
Title
Guardians of the Galaxy             James Gunn
Prometheus                        Ridley Scott
Split                       M. Night Shyamalan
Sing                      Christophe Lourdelet
Suicide Squad                       David Ayer
...                                        ...
Resident Evil: Afterlife    Paul W.S. Anderson
Project X                      Nima Nourizadeh
Hostel: Part II                       Eli Roth
Step Up 2: The Streets              Jon M. Chu
Nine Lives                    Barry Sonnenfeld

                                                                     actors  \
Title
Guardians of the Galaxy   Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...
Prometheus                Noomi Rapace, Logan Marshall-Green, Michael Fa...
Split                     James McAvoy, Anya Taylor-Joy, Haley Lu Richar...
Sing                      Matthew McConaughey,Reese Witherspoon, Seth Ma...
Suicide Squad             Will Smith, Jared Leto, Margot Robbie, Viola D...
...                                                                     ...
Resident Evil: Afterlife  Milla Jovovich, Ali Larter, Wentworth Miller,K...
Project X                 Thomas Mann, Oliver Cooper, Jonathan Daniel Br...
Hostel: Part II           Lauren German, Heather Matarazzo, Bijou Philli...
Step Up 2: The Streets    Robert Hoffman, Briana Evigan, Cassie Ventura,...
Nine Lives                Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...

                          year  runtime  rating   votes  revenue_millions  \
Title
Guardians of the Galaxy   2014      121     8.1  757074            333.13
Prometheus                2012      124     7.0  485820            126.46
Split                     2016      117     7.3  157606            138.12
Sing                      2016      108     7.2   60545            270.32
Suicide Squad             2016      123     6.2  393727            325.02
...                        ...      ...     ...     ...               ...
Resident Evil: Afterlife  2010       97     5.9  140900             60.13
Project X                 2012       88     6.7  164088             54.72
Hostel: Part II           2007       94     5.5   73152             17.54